### ISSUE TITLE
Spike - Look into adding color tokens to Storybook

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-library#302]
While working on the design token documentation, we needed to find a way to display our colors on the doc site. Currently, we are embedding a page from Figma to show all of our primitive, semantic, and component tokens.

In the future, it would be nice to be able to display our colors from Storybook. I found this [API](https://storybook.js.org/docs/api/doc-block-colorpalette#colors) that's supposed to make that easier. Tim suggested creating this spike ticket to look into this and potentially implement it at the same time if it's easy enough.

- [x] Look into this [API](https://storybook.js.org/docs/api/doc-block-colorpalette#colors) and determine if it will work with our tokens and Storybook, and what the level of effort would be to implement it.
- [x] If the LOE is low, consider implementing it with this ticket. Ideally, we'd like the colors to display similarly to the way they're currently displayed in Figma.

**Comment by TimRoe** [comment]
The spike was successful and seems suitable for our purposes!

A branch (`spike/302-ColorTokensInStorybook`) has been created/is outstanding and ready for implementation. Since the further implementation details don't seem too technically challenging, ticket #376 was created for Jessica to handle implementing it--simplifying the process by allowing design to directly structure as they see fit instead of needing to communicate it to engineering.
