### ISSUE TITLE
DS - SnackBar Component Analytics Support

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#367]
As an owner of the app, I want to have access to the interaction analytics of the SnackBar component, so that I can make data-based decisions.

As part of this story we want to allow the SnackBar to pass analytics data to the app

#Acceptance Criteria
- [ ] Add function passthroughs for apps to be able to log analytics based on interactions handled by the SnackBar component

**Comment by TimRoe** [comment]
Closing out this ticket.

While flagship does have analytics for Snackbar, digging deeper I noticed it appears to be just `vama_snackbar_null` which is triggered when the global snackbar is null and [there's](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4496) a [paper trail](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5401) of [3 tickets](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6789) around why that's analytics: some obscure crash where the global snackbar is not set somehow.

The design system Snackbar component is moving away from globally defining and using the provider/hook method instead which should circumvent the null scenario. 

As such, we are excluding analytics for Snackbar as part of MVP since without that null check there's no existing app-level analytics, analytics for calling the Snackbar can be added alongside the hook call, and the Snackbar takes custom onActionPress logic so analytics could be added there as well--leaving the only gap being dismissing a Snackbar, but due to circumstance of use every Snackbar that is opened presumably is dismissed either manually or via navigation so that doesn't seem a useful data point.

This decision can be revisited post-MVP if a need is raised by consumers.
