### ISSUE TITLE
DS - Tech Discovery for Checkbox Group

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#426]
## Description 
This story is to look at the Loading Component to determine any technical complexity we will need to account for during development. 

## Important links
- [Current documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Selection%20and%20Input/Form%20Elements/Checkbox/)
- [Current primary code location]()
- [Current primary test location]()
- [npm package]()
- [Component List](https://docs.google.com/spreadsheets/d/1_EAH2LWSzwF8Om7o4LAYJf6gT9UWENANYpF7SZy3j8w/edit#gid=106854297)

## Design updates
- [Master component](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1415-384&t=giDO64SdmWLSVDDh-4) in Figma (also see [Checkbox Group](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1415-441&t=giDO64SdmWLSVDDh-4))
- [Examples](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1509-5373&t=giDO64SdmWLSVDDh-4) of how the component may appear (also see [Checkbox Group](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1509-7095&t=giDO64SdmWLSVDDh-4))
- [Handoff notes](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=5378-5140&t=giDO64SdmWLSVDDh-4)

## Acceptance Criteria
  

-  [x] Determine the variants needed for the component - just checkBox or checkBox group?
     - [x] Update implementation ticket based on findings
-  [x] Identify any areas that need discussion with the team for MVP scope
-  [x] Create stub stories for any 1-off things needed for the component
-  [x] Determine if the current app form wrapper can be used
-  [ ] ~~create POC to confirm our plans~~

**Comment by narin** [comment]
# Checkbox Technical Discovery

## Current App Usage
- Checkboxes are used in the app in the form of the VASelector component which is used for both Checkboxes and Radio buttons within a FormWrapper
- The default field type for VASelector is Checkbox
- Checkboxes in the form of VASelector are used in the app on the following screens:
  - AskForClaimDecision
  - UploadFile
  - UploadOrAddPhotos
  - EditAddressScreen
  - EditDirectDepositScreen
- In all cases, checkboxes are used as a single checkbox
- RadioGroup also uses VASelector, but for radio buttons only
- Props to deprecate:
  - `labelArgs` isn't used anywhere for checkbox
    - Only used for Address suggestion radio

## va-mobile-library component
- Props
  - `header`: string
  - `checked` bool (`selected` in the app)
  - `label`: (required) string
  - `a11yLabel`: string
  - `hintText`: string
  - `a11yHintText`: string
  - `description`: string
  - `a11yDescription`: string
  - `error`: string. If not null, error state?
  - `disabled`: bool
  - `onChange`: void => () – Fires onClick/onSelect. Required for FormWrapper, potentially analytics
  - `required`: bool. (Required for FormWrapper)
- CheckboxGroup
  - Required to be separate for compatibility with FormWrapper
  - The following is shared at the top instead of being displayed individually for each checkbox: header, hintText, error
  - Passed array of CheckboxProps
    - Restrict unused individual props or ignore them?
- VADS differences
  - Doesn't seem to allow for a single checkbox without a checkbox group label
  - Single checkbox is still within a checkbox group
  - Can we restrict props if checkbox is child of checkbox group?
## Questions for design
- Should there be a disabled state?
- Should there be a "required" prop? VADS has a boolean prop that will display red (*Required) text next to the label and this is a requirement for FormWrapper (at least under the hood)
## Compatibility with FormWrapper
- Should be compatible but requires us to have separate Checkbox and CheckboxGroup components
- FormWrapper will can use single Checkbox and RadioButtons only. Would need significant modification to support groups
- Needs `required` prop as FormWrapper checks if `selected` and `isRequiredField` when submitting a form 
- header, description, and hint wouldn't be displayed without additional modification to VASelector

## New tickets
- Single Checkbox component implementation ticket first before CheckboxGroup

**Comment by jessicawoodin** [comment]
* Should there be a disabled state?
  * Good question. I know from an accessibility perspective, we usually try to avoid disabled states. From what I can tell, I don’t think VADS has a disabled state. Do you know if the app requires a disabled state for any existing use cases? If they don’t, I think I’d prefer not to create one.
* Should there be a "required" prop? VADS has a boolean prop that will display red (*Required) text next to the label and this is a requirement for FormWrapper (at least under the hood)
  * Yes, good catch! They don’t seem to have the Required state in Figma, but I see how it looks in Storybook. I’ll mimic that styling in our component.
