### ISSUE TITLE
DS - Tech Discovery for RadioButton

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#520]
## Description 
This story is to look at the RadioButton Component to determine any technical complexity we will need to account for during development. 

## Important links
- [Current documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Selection%20and%20Input/Form%20Elements/Checkbox/)
- [Current primary code location]()
- [Current primary test location]()
- [npm package]()
- [Component List](https://docs.google.com/spreadsheets/d/1_EAH2LWSzwF8Om7o4LAYJf6gT9UWENANYpF7SZy3j8w/edit#gid=106854297)

## Design updates
- [Master component](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1415-384&t=giDO64SdmWLSVDDh-4) in Figma (also see [Checkbox Group](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1415-441&t=giDO64SdmWLSVDDh-4))
- [Examples](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1509-5373&t=giDO64SdmWLSVDDh-4) of how the component may appear (also see [Checkbox Group](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=1509-7095&t=giDO64SdmWLSVDDh-4))
- [Handoff notes](https://www.figma.com/design/mAMh8vyVgsevAOungfvGN6/%5BNEW%5D-Checkbox?node-id=5378-5140&t=giDO64SdmWLSVDDh-4)

## Acceptance Criteria
  

-  [ ] Determine the variants needed for the component 
     - [ ] Update implementation ticket based on findings
-  [ ] Identify any areas that need discussion with the team for MVP scope
-  [ ] Create stub stories for any 1-off things needed for the component
-  [ ] create POC to confirm our plans (if needed)

**Comment by narin** [comment]
## Technical Discovery
### Implementation
RadioButton will have nearly identical code to Checkbox and be very similar to CheckboxGroup. The majority of the technical discovery is to determine current usage within the app and compatibility with FormWrapper.

### Takeaways
Although FormWrapper supports radio buttons, they are currently not used anywhere within FormWrappers anywhere in the app. Even so, it should be trivial to maintain compatibility with FormWrapper. There is however some complexity with entirely replacing the app's RadioGroup component with our new one. 

RadioGroup is used in 3 spots and can be replaced by our new DS component in 2 of them. The app's RadioGroup component has 2 variants: standard and list. It should be relatively simple to replace the standard variant with our component, but in RX Refill, the filter and sort functionality uses the list variant to display radio buttons as list items with the icon on the right hand side. 

## va-mobile-app notes

- VASelector in form of RadioButton
  - No direct usage in FormWrappers. Only used indirectly as part of RadioGroup 
- RadioGroup
  - Returned by FormWrapper when `FieldType.Radios` is specified
  - List mode and standard mode
    - List mode: Returns list items with radios on right hand side (used in RX filter/sort)
    - Standard mode: Returns list of VASelectors
- RadioGroupModal
  - Displays RadioGroup within a modal in list mode
- FormWrapper
  - RadioGroup (`FieldType.Radios`) not currently used with any instances of FormWrapper
  - VASelector has option to return radio with `FieldType.Selector`, but not currently used anywhere. Only used with RadioGroup
- Current Usage of Radios in App
  - AddressValidation (Edit Address)
    - RadioGroup but not used within FormWrapper
  - GenderIdentityScreen
    - RadioGroup but not used within FormWrapper
  - PrescriptionHistory
    - RadioGroup used as part of RadioGroupModal, but in ListMode, which doesn’t use VASelector. Not used in a FormWrapper
## Notes for App Developers
- `labelArgs` will be removed. Can pass translation directly to `text`
- `disabled` and `notSelectableRadioBtn` won’t be supported
- `additionalLabelText` -> `description`
## Recommendations
- Rename/Replace VASelector with Checkbox only since Radio isn’t used and likely won’t ever be used outside of a group (`FieldType.Radios`)
- Update FormWrapper FieldType `Radios` to return DS RadioButton(s)
- AddressValidation and GenderIdentity: Use DS  RadioButton(s)
- Consider moving “list mode” functionality from RadioGroup to RadioGroupModal. If not, update `getStandardRadioGroup` to return DS RadioButton(s)
